# --- configuration --- #

# --- set to the homeã€€--- #
enable-set-home-sound: true
enable-set-home-delay: false
set-home-delay(s): 5

# --- teleport to the home ---#
enable-teleport-sound: true
enable-teleport-delay: true
teleport-delay(s): 5

# --- generic setting --- #
language(ja, en): en
max-home: 3
move-cancel: true